### ISSUE TITLE
关于这个project的一些问题

### ISSUE THREAD

**Issue by zimenglan-sysu** [baijinping/EmailClient#1]
能不能给我你的联系方式?
另外我想问下 EmailClient 这个源码的一些问题:
1 貌似不能从登录界面转到邮件界面?
2 感觉代码不完整, 收发不了?

谢谢 (我的邮箱: 806617478@qq.com)

**Comment by baijinping** [comment]
这是年初的毕设，后来因为有一些私有文档需要管理，所以放到oschina的私有git上了。我这两天把代码整理下再上传上来

**Comment by baijinping** [comment]
最新的已经上传了
